import '@fortawesome/fontawesome-free/css/all.min.css';

const ProjectCard = ({ title, description, link, hover }) => {
  return (
    <a href={link} target="_blank" rel="noopener noreferrer">
      <div className="relative group p-6 rounded-xl overflow-hidden bg-[#1e1e1e] hover:scale-105 transition-transform duration-300">

        <div className={`absolute inset-0 ${hover} scale-0 origin-bottom-left transition-transform duration-500 ease-out group-hover:scale-150 z-0`} />

        <div className="relative z-10">
          <h3 className="text-2xl font-bold font-[Helvetica_Now_Display] mb-2 text-2xl mb-6 bg-gradient-to-r from-red-500 via-yellow-500 to-blue-500 bg-clip-text text-transparent">
            {title}
          </h3>

          <p className="mt-10 text-xl font-[Helvetica_Now_Display]">
            {description}
          </p>

          <div className="mt-4 flex justify-end">
            <i className="fas fa-external-link-alt text-2xl text-red-500 hover:text-red-400 cursor-pointer transition-colors duration-300"></i>
          </div>
        </div>

      </div>
    </a>
  );
};

const projects = [
  {
    "title": "CodeSphere",
    "description": "An AI Integrated IDE for Faster Development. It's a Coding platform where you can Write/Run/Compile/Debug your Codes. Currently Supporting Languages:- C, C++, Python, JavaScript, Java, Python, PHP, Rust, R, SQL . Other Available: HTML, CSS, Typescript, Ruby, Database languages (SQL, MySQL, SQLite, MongoDB, PostgreSQL, Oracle, Redis), and many more.",
    "link": "https://codespr.netlify.app/",
    "hover": "bg-green-500"
  },
  {
    "title": "FileShare247",
    "description": "Effortlessly Send & Receive Files - Secure, Fast and Hassle-Free! Say goodbye to complicated transfers and enjoy seamless file sharing  anytime, anywhere 🌍! No need for complicated cloud storage setups—just upload your files, share the link, and you're done! Our platform is designed to make file sharing as easy as possible, so you can focus on what really matters, not the tech.",
    "link": "https://fileshare247.netlify.app/",
    "hover": "bg-yellow-500"
  },
  {
    "title": "AceType",
    "description": "AceType is an online typing platform designed to improve typing speed and accuracy. It offers three difficulty levels—Easy, Medium, and Hard—with dynamic typing exercises generated by Google's Gemini API. Users can track their real-time speed (WPM) and accuracy, helping them gradually improve. The simple, UI makes it suitable for typists of all skill levels, from beginners to experts.",
    "link": "https://acetype.netlify.app/",
    "hover": "bg-blue-500"
  },
  {
    "title": "LittleLemon",
    "description": "LittleLemon is a restaurant booking web app that lets users book tables in advance and place orders for dine-in or takeout. With a secure database and intuitive interface, it efficiently manages bookings, orders, and customer data. It also features an interactive map to help users find nearby restaurant locations, offering a modern and reliable solution for both customers and restaurant owners. Built with (Html, Css, Js, Django, Sqlite3).",
    "link": "https://github.com/avinashvermaaa/littlelemon",
    "hover": "bg-green-500"
  },
  {
    "title": "Sorting Visualizer",
    "description": "This project is Engineered for both educational and professional purposes. leverages advanced visualization techniques to illustrate the step-by-step process of various sorting algorithms (Bubble Sort, Insertion Sort, Selection Sort, Quick Sort, Heap Sort, and Shell Sort). By visualizing each algorithm's execution, it provides a deeper understanding of performance, and computational complexity.",
    "link": "https://avinashvermaaa.github.io/Sorting_Visualizer/",
    "hover": "bg-yellow-500"
  },
  {
    "title": "IndieFlix",
    "description": "IndieFlix is an advanced movie streaming platform designed to provide an immersive entertainment experience. Offering a wide range of movies, anime, and web series, the platform ensures high-quality streaming with a seamless, user-friendly interface. It Delivers a smooth and engaging viewing experience across devices, support dynamic content delivery, ensuring users enjoy uninterrupted access to a diverse library of media content.",
    "link": "https://avinashvermaaa.github.io/Indieflix/",
    "hover": "bg-blue-500"
  },
  {
    "title": "Virtual Mouse",
    "description": "This innovative project uses hand gestures to control computer functions in real time. Powered by Python, OpenCV, and NLP, it allows users to navigate and interact with their computer through intuitive gesture-based commands, making the digital experience more interactive and accessible. Virtual Mouse offers a futuristic and hands-free alternative to traditional input methods like mouse, keyboard to save rare earth resources.",
    "link": "https://github.com/avinashvermaaa/Virtual-Mouse",
    "hover": "bg-green-500"
  },
  {
    "title": "Todo List",
    "description": "This efficient Todo List app, built with ReactJS, is designed to help users organize and prioritize tasks seamlessly. Supports features such as filtering tasks by status (completed, pending), sorting by due date, and setting priorities (low, medium, high). Users can also categorize tasks into (general, work, personal, and urgent groups). It also has a dark mode toggle, allowing users to customize the interface for a comfortable viewing experience.",
    "link": "https://todoapp-av.netlify.app/",
    "hover": "bg-yellow-500"
  },
  {
    "title": "QRCode Generator",
    "description": "The QRCode Generator project is a web application that allows users to input a website URL along with a custom image name, and the application generates a QR code based on the provided link. Once the QR code is generated, users can download the image directly to their device. The app leverages JavaScript to dynamically create the QR code and provide a seamless user experience with a clean and simple interface.",
    "link": "https://avinashvermaaa.github.io/qrcode_generator/",
    "hover": "bg-blue-500"
  }
];

function Projects() {

  return (
    <div id="projects" className="w-full min-h-screen bg-[black] text-white px-10 py-20">
      {/* <h2 className="text-6xl text-center mb-16 bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500 bg-clip-text text-transparent">My Projects</h2> */}
      <h2 className="text-6xl text-center mb-16">
        <span className="bg-grad-red bg-clip-text text-transparent inline-block">
          Featured
        </span>{" "}
        <span className="bg-grad-blue bg-clip-text text-transparent inline-block">
          Projects
        </span>
      </h2>

      <div className="grid md:grid-cols-3 gap-10">

        {projects.map((project, index) => (
          <ProjectCard
            key={index}
            title={project.title}
            description={project.description}
            link={project.link}
            hover={project.hover}
          />
        ))}

      </div>
    </div>
  );
}

export default Projects;